version: '3.7'

services:

  hftdb:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - hftnet
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: matthias
      POSTGRES_PASSWORD: passw0rd
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata

  hftbackend:
    image: maeddes/hftbackend:v1
    networks:
      - hftnet
    environment:
      SERVER_PORT: 8090
      SPRING_DATASOURCE_URL: jdbc:postgresql://hftdb:5432/tododb
    ports:
      - 8090:8090

networks:
  hftnet:
    name: hftnet

volumes:
  postgres:
    name: postgres